output_dir_model_rf_detr: models/rf_detr # need
output_dir_model_patchcore : models/patchcore
output_inference_dir: results # need
for_prediction: data/raw/input_data # need
export_ai_csv_files: false # need
roi_config:
  - x_min: 127
    x_max: 294
    y_min: 448
    y_max: 576
    name: "left"
  - x_min: 733
    x_max: 900
    y_min: 448
    y_max: 576
    name: "right"
rf_detr_checkpoint: checkpoint_best_total.pth # need
class_label: anode crack  # need
patchcore_threshold: 2.5 # need
rf_detr_threshold: 0.8 # need
resize_size: [168, 128] # need
filter_index_range: # need
  min: 215
  max: 222


