annotations_root: data/raw/annotations
images_root: data/raw/converted_pngs_defects
good_images_dir: data/raw/good_high_resolution
converted_png_dir: data/raw/converted_pngs
output_coco_dir: data/processed/output_coco_final
output_dir: data/processed/output
output_patchcore_dir: data/raw
output_dir_model_rf_detr: models/rf_detr
output_dir_model_patchcore : ../models/patchcore
output_inference_dir: ../results
for_prediction: /home/anode-defect-detector/data3/NEGATIVES
export_ai_csv_files: false
roi_config:
  - x_min: 127
    x_max: 294
    y_min: 448
    y_max: 576
    name: "left"
  - x_min: 733
    x_max: 900
    y_min: 448
    y_max: 576
    name: "right"

rf_detr_checkpoint: checkpoint_best_total.pth
class_label: upper crack
patchcore_threshold: 1.5
rf_detr_threshold: 0.8
resize_size: [168, 128]
filter_index_range:
  min: 205
  max: 230


